name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation (Dark Theme)
        uses: Platane/snk@v3
        with:
          github_user_name: Coolgolf1  
          outputs: dist/github-contribution-grid-snake-dark.svg
          color_snake: "#00FF00"  
          color_dots: "#1E1E1E,#333333"  

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake-dark.svg
          git commit -m "Update dark-themed contribution snake" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
